name: deploy

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          conda install -n base -c conda-forge conda-build setuptools_scm anaconda-client -y
          conda config --set anaconda_upload yes
          xvfb-run conda build -c conda-forge conda-recipe
