name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: linux conda build and upload
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda install -n base -c conda-forge boa setuptools_scm anaconda-client -y
          conda config --set anaconda_upload yes
          xvfb-run conda mambabuild -c conda-forge --user ilastik-forge conda-recipe
